### ISSUE TITLE
Failed to load library /home/xxx/catkin_ws/devel/lib//librsband_local_planner.so.

### ISSUE THREAD

**Issue by JWSLAM** [gKouros/rsband_local_planner#11]
Hi gkouros,
When i add your plugin into the navigation package, I came across the problem as title. <br>I can find librsband_local_planner.so, but it seems that ROS try to find this .so in directory<br> `/home/xxx/catkin_ws/devel/lib//` instead of `/home/xxx/catkin_ws/devel/lib/`. <br>How can I fix it? Any suggestion will be highly appricieated!<br>

**Comment by JWSLAM** [comment]
When I search this problem， I find the following QA telling that it might be something to do with OMPL.<br>
[https://answers.ros.org/question/224971/cannot-load-ompl-global-planner-plugin/](url)
<br>But I checked the CMakeList.txt file and find the following lines:

```
target_link_libraries(
  ${PROJECT_NAME}
  ${OMPL_LIBRARIES}
  fuzzylite
  ${catkin_LIBRARIES}
)
```

Is there any idea? <br><br>Thanks!<br>

**Comment by gkouros** [comment]
Hi JWSLAM,

Please provide me with your linux and ros distro.
Also, have you installed ompl?

**Comment by JWSLAM** [comment]
I run ROS Kinetic on Ubuntu 16.04.<br>
And I haved installed ompl according to  the following link<br>
[http://ompl.kavrakilab.org/core/installation.html#ubunturos](url)
<br>I install that according to the `ROS` tab.<br>

**Comment by gkouros** [comment]
Sorry for the late reply. It has been a busy week.
There was a missing dependency to yaml-cpp, which probably caused the linking issue.
I have pushed a fix but first you need to install this dependency.

$ sudo apt install ros-kinetic-yaml-cpp-0-3

Hope that solves your problem.

**Comment by JWSLAM** [comment]
That's all right ! I will really appreciate your reply.
So what I have to do is:<br>

* install ros-kinetic-yaml-cpp-0-3
* git clone the newest commit and catkin_make

Is that right?<br>

**Comment by JWSLAM** [comment]
Hi gkouros!<br>
Now I am able to launch the rsband_local_planner.<br>
But when I give a navigation goal by Rviz ， I come across errors saying：<br>
* Setting plan to Elastic Band failed
* Failed to pass global plan to the controller , aborting.

Will you point out a direction how to fix this?
Thank you very much!

**Comment by gkouros** [comment]
What global planner do you use?
And have you properly configured the local and global costmaps?

**Comment by JWSLAM** [comment]
I use `navfn/NavfnROS` as my global planner plugin.
And about costmaps configuration, what do you mean by `properly configured`?
I am sure that it went well when I used `dwa_local_planner`. Is there some tips to check if the costmaps are configured properly?

**Comment by gkouros** [comment]
If dwa worked fine, then the costmaps are probably setup correctly. Can you also test
your setup with eband_local_planner and tell me if it works fine as well?

**Comment by JWSLAM** [comment]
I've tested eband_local_palnner and it went well.
But when I use your git and give it a goal, it keeps acknowledging:
```
[ WARN] [1521465181.387382334, 14717.596000000]: Band is broken. Could not close gaps in converted path. Path not set. Global replanning needed
[ WARN] [1521465181.396921777, 14717.603000000]: Band is broken. Could not close gaps in converted path. Path not set. Global replanning needed
[ERROR] [1521465181.397031053, 14717.603000000]: Setting plan to Elastic Band failed!
[ERROR] [1521465181.397123270, 14717.603000000]: Failed to pass global plan to the controller, aborting.
```

**Comment by gkouros** [comment]
It's the first time I'm seeing this error. I'll need a few things from you to try to recreate the error
and finally debug it:

- rviz screenshot (including global path, local path, robot footprint and map)
- move_base console output
- global and local costmap configurations
- move_base, global and local planner configurations

Also, how did you install eband_local_planner? From a repo, then which repo or from the binaries?

**Comment by JWSLAM** [comment]
Sorry to post the materials late!

- As can be seen in  ![rivz screenshot one](https://github.com/JWSLAM/image/blob/master/1.png), after I send a goal by Rviz there is not global path as well as local path. The Turtlebot stay still doing nothing. When I choose `/move_base/NavfnROS/plan` rather than `/move_base/RSBandPlannerROS/global_plan`  as the global plan topic, I can see the path showed as green in  ![rivz screenshot two](https://github.com/JWSLAM/image/blob/master/2.png), still the Turtlebot could not move.

- Then the move_base console output is like this : ![move_base console](https://github.com/JWSLAM/image/blob/master/3.png).

- Global and local costmap configurations

global_costmap_params.yaml:
```yaml
global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 1.0
   publish_frequency: 0.5
   static_map: true
   transform_tolerance: 0.5
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
```
local_costmap_params.yaml:
```yaml
local_costmap:
   global_frame: odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 4.0
   height: 4.0
   resolution: 0.05
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
```

- Move_base and global planner  configurations

move_base_params.yaml:
```yaml
# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0


planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "rsband_local_planner/RSBandPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner


#We plan to integrate recovery behaviors for turtlebot but currently those belong to gopher and still have to be adapted.
## recovery behaviors; we avoid spinning, but we need a fall-back replanning
#recovery_behavior_enabled: true

#recovery_behaviors:
  #- name: 'super_conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation1'
    #type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
    #type: 'rotate_recovery/RotateRecovery'

#super_conservative_reset1:
  #reset_distance: 3.0
#conservative_reset1:
  #reset_distance: 1.5
#aggressive_reset1:
  #reset_distance: 0.0
#super_conservative_reset2:
  #reset_distance: 3.0
#conservative_reset2:
  #reset_distance: 1.5
#aggressive_reset2:
  #reset_distance: 0.0
```
global_planner_params.yaml:
```yaml

GlobalPlanner:                                  # Also see: http://wiki.ros.org/global_planner
  old_navfn_behavior: false                     # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  use_quadratic: true                           # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_dijkstra: true                            # Use dijkstra's algorithm. Otherwise, A*, default true
  use_grid_path: false                          # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  
  allow_unknown: true                           # Allow planner to plan through unknown space, default true
                                                #Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  planner_window_x: 0.0                         # default 0.0
  planner_window_y: 0.0                         # default 0.0
  default_tolerance: 0.0                        # If goal in obstacle, plan to the closest point in radius default_tolerance, default 0.0
  
  publish_scale: 100                            # Scale by which the published potential gets multiplied, default 100
  planner_costmap_publish_frequency: 0.0        # default 0.0
  
  lethal_cost: 253                              # default 253
  neutral_cost: 50                              # default 50
  cost_factor: 3.0                              # Factor to multiply each cost from costmap by, default 3.0
  publish_potential: true                       # Publish Potential Costmap (this is not like the navfn pointcloud2 potential), default true
```

Then I want to ask which files you mean by `lobal planner configuration`.
I am not sure if the above files could help, but I really want to thank you for your kindness and patience.
